import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Navbar from "@/components/mainPageComponents/Navbar";
import LenisProvider from "@/components/providers/lenis";
import ScrollSmootherWrapper from "@/components/providers/lenis";
import FooterSection from "@/components/mainPageComponents/FooterSection";
import CustomCursor from "@/components/animeComponents/mouse";
import ClientLayout from "@/components/providers/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const futura = localFont({
  variable: "--font-futura",
  src: './fonts/Futura-Bold.woff2'
});
const social = localFont({
  variable: "--font-social",
  src: './fonts/ABCSocialMono-Regular.woff2'
});
const helvic = localFont({
  variable: "--font-helvic",
  src: './fonts/HelveticaNowText-Regular.woff2'
});


export const metadata: Metadata = {
  title: "No Good Co.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${futura.variable} ${helvic.variable} ${geistMono.variable} ${social.variable} text-background antialiased bg-foreground`}
      >
        <ClientLayout>
          <Navbar />
          <ScrollSmootherWrapper>
            {children}
            <FooterSection />
          </ScrollSmootherWrapper>
        </ClientLayout>
      </body>
    </html>
  );
}
